
services:
  manager-db:
    image: postgres:14-alpine # Usamos una imagen oficial de PostgreSQL
    container_name: manager-db
    environment:
      POSTGRES_USER: manager_user
      POSTGRES_PASSWORD: manager_password
      POSTGRES_DB: manager_db
    ports:
      - "5432:5432" # Expone el puerto para que puedas conectarte desde tu máquina si lo necesitas
    volumes:
      - manager-db-data:/var/lib/postgresql/data # Persiste los datos
    networks:
      - jornada-network

  manager:
    build:
      context: ./services/manager-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
      - DB_HOST=manager-db
      - DB_PORT=5432
      - DB_USERNAME=manager_user
      - DB_PASSWORD=manager_password
      - DB_DATABASE=manager_db
      - RABBITMQ_URL=amqps://vukbegwv:kxqAZM3JBKQBuOj2r2q_PcE8CEzhcU7U@shrimp.rmq.cloudamqp.com/vukbegwv
    volumes:
      - ./services/manager-service/src:/app/src
    depends_on:
      manager-db:
        condition: service_started
    networks:
      - jornada-network

  kitchen-db:
    image: postgres:14-alpine
    container_name: kitchen-db
    environment:
      POSTGRES_USER: kitchen_user
      POSTGRES_PASSWORD: kitchen_password
      POSTGRES_DB: kitchen_db
    volumes:
      - kitchen-db-data:/var/lib/postgresql/data
    networks:
      - jornada-network

  kitchen:
    build:
      context: ./services/kitchen-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=manager-db
      - DB_PORT=5432
      - DB_USERNAME=manager_user
      - DB_PASSWORD=manager_password
      - DB_DATABASE=manager_db
      - RABBITMQ_URL=amqps://vukbegwv:kxqAZM3JBKQBuOj2r2q_PcE8CEzhcU7U@shrimp.rmq.cloudamqp.com/vukbegwv
    volumes:
      - ./services/kitchen-service/src:/app/src
    depends_on:
      kitchen-db:
        condition: service_started
    networks:
      - jornada-network

  warehouse-db:
    image: postgres:14-alpine
    container_name: warehouse-db
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_password
      POSTGRES_DB: warehouse_db
    ports:
      - "5433:5432"
    volumes:
      - warehouse-db-data:/var/lib/postgresql/data
    networks:
      - jornada-network

  warehouse:
    build:
      context: ./services/warehouse-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=manager-db
      - DB_PORT=5432
      - DB_USERNAME=manager_user
      - DB_PASSWORD=manager_password
      - DB_DATABASE=manager_db
      - RABBITMQ_URL=amqps://vukbegwv:kxqAZM3JBKQBuOj2r2q_PcE8CEzhcU7U@shrimp.rmq.cloudamqp.com/vukbegwv
    volumes:
      - ./services/warehouse-service/src:/app/src
    depends_on:
      warehouse-db:
        condition: service_started
    networks:
      - jornada-network

  marketplace:
    build:
      context: ./services/marketplace-service
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqps://vukbegwv:kxqAZM3JBKQBuOj2r2q_PcE8CEzhcU7U@shrimp.rmq.cloudamqp.com/vukbegwv
      - ALEGRA_EXTERNAL_MARKETPLACE_API= https://recruitment.alegra.com/api/farmers-market/buy
    volumes:
      - ./services/marketplace-service/src:/app/src
    networks:
      - jornada-network

volumes:
  manager-db-data:
  warehouse-db-data:
  kitchen-db-data:

networks:
  jornada-network:
    driver: bridge
