
services:
  # frontend:
  #   build:
  #     context: ./services/frontend-service
  #     dockerfile: Dockerfile.dev
  #   container_name: frontend-service
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./services/frontend-service:/app
  #     - /app/node_modules
  #   networks:
  #     - jornada-network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-service
    hostname: rabbitmq
    ports:
      - "5672:5672"     # Puerto para mensajes
      - "15672:15672"   # Puerto para Interfaz web de administraci칩n
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jornada-network

  manager-db:
    image: postgres:14-alpine # Usamos una imagen oficial de PostgreSQL
    container_name: manager-db
    environment:
      POSTGRES_USER: manager_user
      POSTGRES_PASSWORD: manager_password
      POSTGRES_DB: manager_db
    ports:
      - "5432:5432" # Expone el puerto para que puedas conectarte desde tu m치quina si lo necesitas
    volumes:
      - manager-db-data:/var/lib/postgresql/data # Persiste los datos
    networks:
      - jornada-network

  # dozzle:
  #   container_name: dozzle
  #   image: amir20/dozzle:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - "8888:8080" # Accede a Dozzle en localhost:8888

  manager:
    build:
      context: ./services/manager-service
      dockerfile: Dockerfile.dev
    # container_name: manager-service
    ports:
      - "3001:3001"
    environment:
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
      - PORT= 3001
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - DB_HOST=manager-db
      - DB_PORT=5432
      - DB_USERNAME=manager_user
      - DB_PASSWORD=manager_password
      - DB_DATABASE=manager_db
    volumes:
      - ./services/manager-service/src:/app/src
    depends_on:
      rabbitmq:
        condition: service_healthy
      manager-db:
        condition: service_started
    networks:
      - jornada-network

  kitchen-db:
    image: postgres:14-alpine # Usamos una imagen oficial de PostgreSQL
    container_name: kitchen-db
    environment:
      POSTGRES_USER: kitchen_user
      POSTGRES_PASSWORD: kitchen_password
      POSTGRES_DB: kitchen_db
    ports:
      - "5434:5432" # Expone el puerto para que puedas conectarte desde tu m치quina si lo necesitas
    volumes:
      - kitchen-db-data:/var/lib/postgresql/data # Persiste los datos
    networks:
      - jornada-network

  kitchen:
    build:
      context: ./services/kitchen-service
      dockerfile: Dockerfile.dev
    # container_name: kitchen-service
    # ports:
    #   - "3002:3002"
    environment:
      # - PORT= 3002
      - RABBITMQ_URL= amqp://admin:admin@rabbitmq:5672
      - DB_HOST=kitchen-db
      - DB_PORT=5432
      - DB_USERNAME=kitchen_user
      - DB_PASSWORD=kitchen_password
      - DB_DATABASE=kitchen_db
    volumes:
      - ./services/kitchen-service/src:/app/src
    depends_on:
      rabbitmq:
        condition: service_healthy
      kitchen-db:
        condition: service_started
    networks:
      - jornada-network

  warehouse-db:
    image: postgres:14-alpine # Usamos una imagen oficial de PostgreSQL
    container_name: warehouse-db
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_password
      POSTGRES_DB: warehouse_db
    ports:
      - "5433:5432" # Expone el puerto para que puedas conectarte desde tu m치quina si lo necesitas
    volumes:
      - warehouse-db-data:/var/lib/postgresql/data # Persiste los datos
    networks:
      - jornada-network

  warehouse:
    build:
      context: ./services/warehouse-service
      dockerfile: Dockerfile.dev
    # container_name: warehouse-service
    # ports:
      # - "3003:3003"
    environment:
      # - PORT= 3003
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - DB_HOST=warehouse-db
      - DB_PORT=5432
      - DB_USERNAME=warehouse_user
      - DB_PASSWORD=warehouse_password
      - DB_DATABASE=warehouse_db
    volumes:
      - ./services/warehouse-service/src:/app/src
    depends_on:
      rabbitmq:
        condition: service_healthy
      warehouse-db:
        condition: service_started
    networks:
      - jornada-network

  marketplace:
    build:
      context: ./services/marketplace-service
      dockerfile: Dockerfile.dev
    # container_name: marketplace-service
    # ports:
    #   - "3004:3004"
    environment:
      # - PORT= 3004
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - ALEGRA_EXTERNAL_MARKETPLACE_API= https://recruitment.alegra.com/api/farmers-market/buy
    volumes:
      - ./services/marketplace-service/src:/app/src
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - jornada-network

volumes:
  manager-db-data:
  warehouse-db-data:
  kitchen-db-data:

networks:
  jornada-network:
    driver: bridge
