services:
  frontend:
    build:
      context: ./services/frontend-service
      dockerfile: Dockerfile
    environment:
      VITE_BACKEND_API_URL: http://localhost:3001/api
    volumes:
      - ./services/frontend-service:/app
      - /app/node_modules
    depends_on:
      manager:
        condition: service_started
    networks:
      - jornada-network
  
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-service
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jornada-network

  manager-db:
    image: postgres:14-alpine # Usamos una imagen oficial de PostgreSQL
    container_name: manager-db
    environment:
      POSTGRES_USER: manager_user
      POSTGRES_PASSWORD: manager_password
      POSTGRES_DB: manager_db
    ports:
      - "5432:5432" # Expone el puerto para que puedas conectarte desde tu máquina si lo necesitas
    volumes:
      - manager-db-data:/var/lib/postgresql/data # Persiste los datos
    networks:
      - jornada-network

  manager:
    build:
      context: ./services/manager-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
      - DATABASE_URL=postgres://manager_user:manager_password@manager-db:5432/manager_db
      - RABBITMQ_URL= amqp://admin:admin@rabbitmq:5672
    volumes:
      - ./services/manager-service/src:/app/src
    depends_on:
      rabbitmq:
        condition: service_healthy
      manager-db:
        condition: service_started
    networks:
      - jornada-network

  kitchen-db:
    image: postgres:14-alpine
    container_name: kitchen-db
    environment:
      POSTGRES_USER: kitchen_user
      POSTGRES_PASSWORD: kitchen_password
      POSTGRES_DB: kitchen_db
    volumes:
      - kitchen-db-data:/var/lib/postgresql/data
    networks:
      - jornada-network

  kitchen:
    build:
      context: ./services/kitchen-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://kitchen_user:kitchen_password@kitchen-db:5432/kitchen_db
      - RABBITMQ_URL= amqp://admin:admin@rabbitmq:5672
    volumes:
      - ./services/kitchen-service/src:/app/src
    depends_on:
      rabbitmq:
        condition: service_healthy
      kitchen-db:
        condition: service_started
    networks:
      - jornada-network

  warehouse-db:
    image: postgres:14-alpine
    container_name: warehouse-db
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_password
      POSTGRES_DB: warehouse_db
    ports:
      - "5433:5432"
    volumes:
      - warehouse-db-data:/var/lib/postgresql/data
    networks:
      - jornada-network

  warehouse:
    build:
      context: ./services/warehouse-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=manager-db
      - DB_PORT=5432
      - DB_USERNAME=manager_user
      - DB_PASSWORD=manager_password
      - DB_DATABASE=manager_db
      - RABBITMQ_URL= amqp://admin:admin@rabbitmq:5672
    volumes:
      - ./services/warehouse-service/src:/app/src
    depends_on:
      rabbitmq:
        condition: service_healthy
      warehouse-db:
        condition: service_started
    networks:
      - jornada-network

  marketplace:
    build:
      context: ./services/marketplace-service
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL= amqp://admin:admin@rabbitmq:5672
      - ALEGRA_EXTERNAL_MARKETPLACE_API= https://recruitment.alegra.com/api/farmers-market/buy
    volumes:
      - ./services/marketplace-service/src:/app/src
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - jornada-network

volumes:
  manager-db-data:
  warehouse-db-data:
  kitchen-db-data:

networks:
  jornada-network:
    driver: bridge
