databases:
  - name: manager-db
    plan: free
    postgresMajorVersion: "14"

services:
  # --- API del Manager ---
  - name: manager-service
    type: web
    plan: free
    runtime: docker
    dockerContext: ./services/manager-service
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: manager-db
          property: connectionString
      - key: RABBITMQ_URL
        sync: false