databases:
  - name: manager-db
    plan: starter
    postgresMajorVersion: "14"
  - name: kitchen-db
    plan: starter
    postgresMajorVersion: "14"

services:
  # --- API del Manager ---
  - name: manager-service
    type: web
    plan: starter
    runtime: docker
    dockerContext: ./services/manager-service
    dockerfilePath: ./services/manager-service/Dockerfile
    envVars:
      - key: CORS_ORIGINS
        sync: false
      - key: MANAGER_DATABASE_URL
        fromDatabase:
          type: pserv
          name: manager-db
          property: connectionString
      - fromGroup: jornada-secrets
  
  - name: kitchen-service
    type: web
    plan: starter
    runtime: docker
    dockerContext: ./services/kitchen-service
    dockerfilePath: ./services/kitchen-service/Dockerfile
    envVars:
      - key: MANAGER_DATABASE_URL
        fromDatabase:
          type: pserv
          name: kitchen-db
          property: connectionString
      - fromGroup: jornada-secrets