services:
  # --- API del Manager ---
  - name: manager-service
    type: web
    plan: free
    runtime: docker
    dockerContext: ./services/manager-service
    dockerfilePath: ./services/manager-service/Dockerfile
    envVars:
      - key: CORS_ORIGINS
        sync: false
      - key: MANAGER_DATABASE_URL
        sync: false
      - fromGroup: jornada-secrets
  
  - name: kitchen-service
    type: web
    plan: free
    runtime: docker
    dockerContext: ./services/kitchen-service
    dockerfilePath: ./services/kitchen-service/Dockerfile
    envVars:
      - key: KITCHEN_DATABASE_URL
        sync: false
      - fromGroup: jornada-secrets